name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish-nuget:
    if: github.event.pull_request.merged == true
    name: Publish Nuget Package
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=1.1.{vers.PACKAGEVERSIONPATCHNUMBER}
    - name: Publish NuGet Package
      run: dotnet pack
    - name: Prep packages
      run: dotnet nuget add source --username llott9264 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/llott9264/index.json"
    - name: Publish NuGet Package to GitHub
      run: dotnet nuget push Utilities.Email/bin/Release/Utilities.Email*.nupkg --api-key ${{ secrets.NUGETPUBLISHTOKEN }}  --source "github"
  pull-request-not-merged:
    if: github.event.pull_request.merged == false
    name: Cancel Nuget Package Release
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo Pull Request was not merged with main branch.  Release was canceled.
