name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  publish-nuget:
    name: Publish Nuget Package
    runs-on: windows-latest    
    env:
      BUILD_CONFIG: Release
      PACKAGE_VERSION: 1.2.${{ github.run_number }}
      GITHUB_NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_NUGET_URL: https://nuget.pkg.github.com/llott9264/index.json
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'
    - name: CLean 
      run: dotnet clean -c ${{ env.BUILD_CONFIG }} && dotnet nuget locals all --clear
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration ${{ env.BUILD_CONFIG }} --no-restore

    - name: Publish NuGet Package
      run: dotnet pack /p:Version=${{ env.PACKAGE_VERSION }}
      
    - name: Prep packages
      run: dotnet nuget add source --username llott9264 --password ${{ env.GITHUB_NUGET_API_KEY }} --store-password-in-clear-text --name github ${{ env.GITHUB_NUGET_URL }}
      
    - name: Publish NuGet Package to GitHub
      run: dotnet nuget push Utilities.Email.${{ env.PACKAGE_VERSION }}.nupkg --api-key ${{ env.GITHUB_NUGET_API_KEY }}  --source "github" --skip-duplicate
